---
author: Paulo F. Oliveira
branding:
  color: blue
  icon: code
description: >
  Parse a `.tool-versions` file (as specified by `asdf`) and make tool/versions available as outputs
  from an identified step.
name: "@paulo-ferraz-oliveira/parse-tool-versions"
runs:
  main: dist/index.mjs
  using: node20
