---
name: Windows CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  windows-ci:
    name: Windows CI

    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - id: tool-versions
        name: Parse .tool-versions
        uses: ./

      - name: Test for bash
        shell: bash
        run: |
          RUBY=${{steps.tool-versions.outputs.example-ruby}}
          NPM=${{steps.tool-versions.outputs.example-npm}}
          PYTHON=${{steps.tool-versions.outputs.example-python}}
          NODEJS=${{steps.tool-versions.outputs.example-nodejs}}
          echo "${RUBY?output not set}"
          echo "${NPM?output not set}"
          echo "${PYTHON?output not set}"
          echo "${NODEJS?output not set}"

      - name: Test for pwsh
        shell: pwsh
        run: |
          $Env:RUBY="${{steps.tool-versions.outputs.example-ruby}}"
          $Env:NPM="${{steps.tool-versions.outputs.example-npm}}"
          $Env:PYTHON="${{steps.tool-versions.outputs.example-python}}"
          $Env:NODEJS="${{steps.tool-versions.outputs.example-nodejs}}"
          Test-Path $Env:RUBY
          Test-Path $Env:NPM
          Test-Path $Env:PYTHON
          Test-Path $Env:NODEJS

      - name: Test for cmd
        shell: cmd
        run: |
          set RUBY=${{steps.tool-versions.outputs.example-ruby}}
          set NPM=${{steps.tool-versions.outputs.example-npm}}
          set PYTHON=${{steps.tool-versions.outputs.example-python}}
          set NODEJS=${{steps.tool-versions.outputs.example-nodejs}}
          if "%RUBY%" == "" exit 1
          if "%NPM%" == "" exit 1
          if "%PYTHON%" == "" exit 1
          if "%NODEJS%" == "" exit 1

      - name: Test for powershell
        shell: powershell
        run: |
          $Env:RUBY="${{steps.tool-versions.outputs.example-ruby}}"
          $Env:NPM="${{steps.tool-versions.outputs.example-npm}}"
          $Env:PYTHON="${{steps.tool-versions.outputs.example-python}}"
          $Env:NODEJS="${{steps.tool-versions.outputs.example-nodejs}}"
          Test-Path $Env:RUBY
          Test-Path $Env:NPM
          Test-Path $Env:PYTHON
          Test-Path $Env:NODEJS
